kramdown:
  input: GFM

site:
  url: "http://www.lolupdater.com"
  name: "LoLUpdater"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

gems:
  - jekyll-redirect-from

exclude: node_modules
